### ISSUE TITLE
URS Proxy not Working as Expected

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-CIDA/geo-data-portal#237]
Coming back to work on some NASA datasets... It appears that the URS implementation hasn't quite kept up iwth NASA's implementation?

Using this XML as interrogate.xml

```
<?xml version="1.0" encoding="utf-8"?>
<wps:Execute service="WPS" version="1.0.0" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsExecute_request.xsd">
		<ows:Identifier>gov.usgs.cida.gdp.wps.algorithm.discovery.InterrogateDataset</ows:Identifier>
		<wps:DataInputs>
				<wps:Input>
						<ows:Identifier>DATASET_URI</ows:Identifier>
						<wps:Data>
								<wps:LiteralData>http://hydro1.sci.gsfc.nasa.gov/dods/GLDAS_NOAH025_M.020</wps:LiteralData>
						</wps:Data>
				</wps:Input>
		</wps:DataInputs>
		<wps:ResponseForm>
			<wps:RawDataOutput mimeType="text/plain">
				<ows:Identifier>PROXY_URL</ows:Identifier>
			</wps:RawDataOutput>
		</wps:ResponseForm>
</wps:Execute>
```

I do: `curl -X POST -d @interrogate.xml --header "Content-Type:text/xml" http://cida.usgs.gov/gdp/utility/WebProcessingService` 

and get:

```
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" version="1.0.0">
  <ows:Exception exceptionCode="NoApplicableCode">
    <ows:ExceptionText>Error while executing the embedded process for: gov.usgs.cida.gdp.wps.algorithm.discovery.InterrogateDataset</ows:ExceptionText>
  </ows:Exception>
  <ows:Exception exceptionCode="JAVA_StackTrace">
    <ows:ExceptionText>org.n52.wps.server.ExceptionReport: Error while executing the embedded process for: gov.usgs.cida.gdp.wps.algorithm.discovery.InterrogateDataset
	at org.n52.wps.server.request.ExecuteRequest.call(ExecuteRequest.java:716)
	at org.n52.wps.server.request.ExecuteRequest.call(ExecuteRequest.java:92)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Currently only URS endpoints are supported
	at org.n52.wps.algorithm.annotation.AnnotationBinding$ExecuteMethodBinding.execute(AnnotationBinding.java:96)
	at org.n52.wps.server.AbstractAnnotatedAlgorithm.run(AbstractAnnotatedAlgorithm.java:54)
	at org.n52.wps.server.request.ExecuteRequest.call(ExecuteRequest.java:685)
	... 5 more
Caused by: java.lang.UnsupportedOperationException: Currently only URS endpoints are supported
	at gov.usgs.cida.gdp.wps.algorithm.discovery.InterrogateDataset.process(InterrogateDataset.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.n52.wps.algorithm.annotation.AnnotationBinding$ExecuteMethodBinding.execute(AnnotationBinding.java:89)
	... 7 more</ows:ExceptionText>
  </ows:Exception>
  <ows:Exception exceptionCode="JAVA_RootCause">
    <ows:ExceptionText>Currently only URS endpoints are supported</ows:ExceptionText>
    <ows:ExceptionText>java.lang.RuntimeException: Currently only URS endpoints are supported
	at org.n52.wps.algorithm.annotation.AnnotationBinding$ExecuteMethodBinding.execute(AnnotationBinding.java:96)
	at org.n52.wps.server.AbstractAnnotatedAlgorithm.run(AbstractAnnotatedAlgorithm.java:54)
	at org.n52.wps.server.request.ExecuteRequest.call(ExecuteRequest.java:685)
	at org.n52.wps.server.request.ExecuteRequest.call(ExecuteRequest.java:92)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: Currently only URS endpoints are supported
	at gov.usgs.cida.gdp.wps.algorithm.discovery.InterrogateDataset.process(InterrogateDataset.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.n52.wps.algorithm.annotation.AnnotationBinding$ExecuteMethodBinding.execute(AnnotationBinding.java:89)
	... 7 more</ows:ExceptionText>
  </ows:Exception>
```

**Comment by dblodgett-usgs** [comment]
@jiwalker-usgs Can you take a look at this quick? Do you know if the redirect / authentication behavior is what the proxy code is expecting?
